const dotenv = require('dotenv');

dotenv.config();
module.exports = {
  PORT: process.env.PORT,
  PASSWORD: process.env.PASSWORD,
  DBNAME: process.env.DBNAME,
  USER: process.env.DBUSER,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_SERVICE_SID: process.env.TWILIO_SERVICE_SID,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  B4B_WEBSERVICES_USERNAME: process.env.B4B_WEBSERVICES_USERNAME,
  B4B_WEBSERVICES_PASSWORD: process.env.B4B_WEBSERVICES_PASSWORD,
  MAMBU_WEBSERVICES_USERNAME: process.env.MAMBU_WEBSERVICES_USERNAME,
  MAMBU_WEBSERVICES_PASSWORD: process.env.MAMBU_WEBSERVICES_PASSWORD,
};
